version: 2.1
jobs: 
  test: 
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment: 
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
          PGHOST: 127.0.0.1
          PGUSER: deploy
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: deploy
          POSTGRES_DB: bookapp_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Bundler を指定
          command: bundle -v

      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Install Bundle
          command: bundle check || bundle install

      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-

      - run:
          name: Install Yarn
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait For DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Setup DB
          command: bundle exec rails db:schema:load --trace

      - run:
          name: Test rails
          command: |
            bundle exec rails test          
            bundle exec rails test:system

      - store_test_results: 
          path: test_results

workflows:
  version: 2
  test:
    jobs:
      - test

