version: 2.1

orbs:
  ruby: circleci/ruby@1.0 
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout 
      - ruby/install-deps 
      - node/install-packages: 
          pkg-manager: yarn
          cache-key: "yarn.lock"
          
  test: 
    parallelism: 3 
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    steps:
      - checkout 
      - ruby/install-deps 
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: run test
          command: bundle exec rails test

workflows:
  version: 2
  build_and_test:     
    jobs:            
      - build       
      - test:      
          requires:
            - build 
